In [1]:
import numpy as np
A = np.arange(64).reshape(8,8)
for i in range(0, 8):
    for j in range(0, 8):
        if i % 2 == 0 and j % 2 == 0 or i % 2 == 1 and j % 2 == 1:
            A[i][j] = 0
        else:
            A[i][j] = 1
print(A)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [2]:
import numpy as np
A = np.arange(25).reshape(5,5)
for i in range(0, 5):
    for j in range(0, 5):
        A[i][j] = j
print(A)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [4]:
import numpy as np
A = np.arange(27).reshape(3, 3, 3)
print(A)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [6]:
import numpy as np
n = int(input())
A = np.arange(n*n).reshape(n,n)
for i in range(0, n):
    for j in range(0, n):
        if i == 0 or j == 0 or i == n-1 or j == n-1:
            A[i][j] = 1
        else:
            A[i][j] = 0
print(A)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [8]:
import numpy as np
A = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(A)
print(np.sort(A))

[2 1 5 3 7 4 6 8]
[1 2 3 4 5 6 7 8]


In [10]:
n = int(input())
m = int(input())
a = np.arange(n*m).reshape(n,m)
print(a)
print(n*m)
print(n,"x",m)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
25
5 x 5


In [11]:
import pandas as pd
import math as m
a = int(input())
b = int(input())
s1 = pd.Series([a,b])
print(m.sqrt(s1[0]*s1[0]+s1[1]*s1[1]))

7.0710678118654755


In [12]:
import pandas as pd
url = 'https://raw.githubusercontent.com/akmand/datasets/main/cll111.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)

1         2        3         4         5          6        7  \
0  4551.050   778.070  529.383  1579.939  4431.281  26528.738  108.939   
1  4894.835   953.012  924.606   609.542  5745.776  25299.391  235.744   
2  7021.420   983.019  634.856   743.686  7059.756  15447.900  176.568   
3  3954.804   623.204  422.608  2444.540  6121.851   8543.166   92.627   
4  4286.958  1046.373  523.819  3114.896  5975.083  58065.282  200.695   

          8          9         10  ...    11332    11333    11334     11335  \
0  1850.430   2316.170  41750.693  ...  215.002  372.668  370.939   317.649   
1  4046.767   3686.428  35744.253  ...  381.188  664.876  318.512   312.896   
2  2007.593   2898.267  19392.063  ...  243.643  391.454  385.735  1210.101   
3  3497.736   2824.900  34124.433  ...  334.072  301.437  115.246   506.503   
4  3091.068  19735.442  51675.471  ...  357.353  257.546  188.657   770.394   

     11336     11337    11338     11339     11340  11341  
0  289.033   288.289  195.372   465.682   717.677      1  
1  124.774   201.921  963.929  1073.766  1165.775      1  
2  993.024   360.058  112.207  1223.602   419.183      1  
3  297.748   406.335  246.898   554.892   381.016      1  
4  410.719  1213.041  819.755   614.679   472.511      1  

[5 rows x 11341 columns]

In [13]:
import pandas as pd
url = 'https://raw.githubusercontent.com/akmand/datasets/main/cll111.csv'
dataframe = pd.read_csv(url)
dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe()
dataframe.iloc[1:4]
dataframe[dataframe['7'] == '176.568'].head(2)

Empty DataFrame
Columns: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, ...]
Index: []

[0 rows x 11341 columns]

In [2]:

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
scaler1 = MinMaxScaler()
scaler2 = StandardScaler()
df = pd.read_csv(url)
df[['sepal_length_cm']] = scaler1.fit_transform(df[['sepal_length_cm']])
df[['sepal_width_cm']] = scaler2.fit_transform(df[['sepal_width_cm']])
df



sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]