In [1]:
import numpy as np
A = np.arange(64).reshape(8,8)
for i in range(0, 8):
    for j in range(0, 8):
        if i % 2 == 0 and j % 2 == 0 or i % 2 == 1 and j % 2 == 1:
            A[i][j] = 0
        else:
            A[i][j] = 1
print(A)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [2]:
import numpy as np
A = np.arange(25).reshape(5,5)
for i in range(0, 5):
    for j in range(0, 5):
        A[i][j] = j
print(A)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [4]:
import numpy as np
A = np.arange(27).reshape(3, 3, 3)
print(A)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [6]:
import numpy as np
n = int(input())
A = np.arange(n*n).reshape(n,n)
for i in range(0, n):
    for j in range(0, n):
        if i == 0 or j == 0 or i == n-1 or j == n-1:
            A[i][j] = 1
        else:
            A[i][j] = 0
print(A)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [8]:
import numpy as np
A = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(A)
print(np.sort(A))

[2 1 5 3 7 4 6 8]
[1 2 3 4 5 6 7 8]


In [10]:
n = int(input())
m = int(input())
a = np.arange(n*m).reshape(n,m)
print(a)
print(n*m)
print(n,"x",m)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
25
5 x 5


In [11]:
import pandas as pd
import math as m
a = int(input())
b = int(input())
s1 = pd.Series([a,b])
print(m.sqrt(s1[0]*s1[0]+s1[1]*s1[1]))

7.0710678118654755


In [12]:
import pandas as pd
url = 'https://raw.githubusercontent.com/akmand/datasets/main/cll111.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)

1         2        3         4         5          6        7  \
0  4551.050   778.070  529.383  1579.939  4431.281  26528.738  108.939   
1  4894.835   953.012  924.606   609.542  5745.776  25299.391  235.744   
2  7021.420   983.019  634.856   743.686  7059.756  15447.900  176.568   
3  3954.804   623.204  422.608  2444.540  6121.851   8543.166   92.627   
4  4286.958  1046.373  523.819  3114.896  5975.083  58065.282  200.695   

          8          9         10  ...    11332    11333    11334     11335  \
0  1850.430   2316.170  41750.693  ...  215.002  372.668  370.939   317.649   
1  4046.767   3686.428  35744.253  ...  381.188  664.876  318.512   312.896   
2  2007.593   2898.267  19392.063  ...  243.643  391.454  385.735  1210.101   
3  3497.736   2824.900  34124.433  ...  334.072  301.437  115.246   506.503   
4  3091.068  19735.442  51675.471  ...  357.353  257.546  188.657   770.394   

     11336     11337    11338     11339     11340  11341  
0  289.033   288.289  195.372   465.682   717.677      1  
1  124.774   201.921  963.929  1073.766  1165.775      1  
2  993.024   360.058  112.207  1223.602   419.183      1  
3  297.748   406.335  246.898   554.892   381.016      1  
4  410.719  1213.041  819.755   614.679   472.511      1  

[5 rows x 11341 columns]

In [13]:
import pandas as pd
url = 'https://raw.githubusercontent.com/akmand/datasets/main/cll111.csv'
dataframe = pd.read_csv(url)
dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe()
dataframe.iloc[1:4]
dataframe[dataframe['7'] == '176.568'].head(2)

Empty DataFrame
Columns: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, ...]
Index: []

[0 rows x 11341 columns]

In [15]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
dataframe = pd.read_csv(url)
feature = np.array(dataframe['sepal_length_cm'])
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))
scaled_feature = minmax_scale.fit_transform(feature)
scaled_feature
feature1 = np.array(dataframe['sepal_width_cm'])
scaler = preprocessing.StandardScaler()
standardized = scaler.fit_transform(feature1)
standardized

ValueError: Expected 2D array, got 1D array instead:
array=[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
 5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
 6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
 6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
 5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
 6.7 6.7 6.3 6.5 6.2 5.9].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.